[package]
name = "ppm"
version = "0.1.0"
authors = ["Chris Paterson <cjpaterson.3@gmail.com>"]
edition = "2018"

[lib]
name = "ppm"
path = "src/lib.rs"

[[bin]]
name = "ppm_test"
path = "src/bin.rs"

[dependencies]
